"""init

Revision ID: 00e6af5f2f0a
Revises: 
Create Date: 2024-11-14 23:11:17.306453

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "00e6af5f2f0a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "news",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("news_pkey")),
    )
    op.create_index(op.f("news_id_idx"), "news", ["id"], unique=False)
    op.create_index(op.f("news_title_idx"), "news", ["title"], unique=False)
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("tags_pkey")),
    )
    op.create_index(op.f("tags_id_idx"), "tags", ["id"], unique=False)
    op.create_index(op.f("tags_title_idx"), "tags", ["title"], unique=False)
    op.create_table(
        "news_and_tags",
        sa.Column("tags_id", sa.Integer(), nullable=False),
        sa.Column("news_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["news_id"], ["news.id"], name=op.f("news_and_tags_news_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["tags_id"], ["tags.id"], name=op.f("news_and_tags_tags_id_fkey")
        ),
        sa.PrimaryKeyConstraint("tags_id", "news_id", name=op.f("news_and_tags_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("news_and_tags")
    op.drop_index(op.f("tags_title_idx"), table_name="tags")
    op.drop_index(op.f("tags_id_idx"), table_name="tags")
    op.drop_table("tags")
    op.drop_index(op.f("news_title_idx"), table_name="news")
    op.drop_index(op.f("news_id_idx"), table_name="news")
    op.drop_table("news")
    # ### end Alembic commands ###
