"""init

Revision ID: 65525b4a9d79
Revises: 
Create Date: 2024-11-10 23:02:14.056358

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65525b4a9d79"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("categories_pkey")),
    )
    op.create_index(op.f("categories_id_idx"), "categories", ["id"], unique=False)
    op.create_index(op.f("categories_name_idx"), "categories", ["name"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("calories", sa.Integer(), nullable=False),
        sa.Column("ingredients", sa.String(), nullable=False),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], name=op.f("products_category_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("products_pkey")),
    )
    op.create_index(op.f("products_id_idx"), "products", ["id"], unique=False)
    op.create_index(op.f("products_name_idx"), "products", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("products_name_idx"), table_name="products")
    op.drop_index(op.f("products_id_idx"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("categories_name_idx"), table_name="categories")
    op.drop_index(op.f("categories_id_idx"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
